"""
Figure 5C — Step 1: raw simulation data for NK directed evolution (rugged, K=25).

Two raw simulation outputs are required:

  SLIDE_data/large_strategy_sweep.pkl  — strategy sweep over NK landscapes
                                          used to derive NK_strategy_spaces.pkl
                                          generated by: scripts/large_strategy_sweep.py

  NK directed evolution results        — produced inline in the data processing
                                          notebook (ruggedness_figures_data_processing.ipynb,
                                          cells 98-102) using JAX DE simulation.
                                          Saved to: plot_data/NK_DE.pkl

Both files ultimately feed into:
  plot_data/NK_DE.pkl              (DE fitness trajectories for K=1 and K=25)
  plot_data/NK_strategy_spaces.pkl (strategy space arrays for K=1 and K=25)

Usage
-----
  Run the strategy sweep script on a GPU before proceeding to step 2:

    python scripts/large_strategy_sweep.py

  Then run the NK directed evolution simulation via:
    ruggedness_figures_data_processing.ipynb cells 98-104

Shared raw data: large_strategy_sweep.pkl is also used by Fig 5A and Fig 5B.
  plot_data/NK_DE.pkl and plot_data/NK_strategy_spaces.pkl are shared with Fig 5B.
"""

print("Raw data needed:")
print("  SLIDE_data/large_strategy_sweep.pkl  (scripts/large_strategy_sweep.py)")
print("  NK DE simulation (ruggedness_figures_data_processing.ipynb cells 98-104)")
