name: SLIDE_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26
  - scipy=1.16
  - pandas=2.3
  - matplotlib=3.10
  - jax=0.4.27
  - jaxlib=0.4.27=*cuda*
  - tqdm=4.67
  - ipykernel=6.29
  - ipywidgets=8.1
  - pytest=8.4
  - pytest-cov=6.2
  - ruff=0.12
