"""Local path configuration helpers.

Several analyses/scripts need access to a larger dataset directory (referred to as
"SLIDE_data") which is typically downloaded from Zenodo or generated by running the
scripts under `scripts/`.

To keep the repository portable, paths are resolved dynamically rather than being
hard-coded.

## Data directory resolution

`get_slide_data_dir()` resolves the SLIDE_data location in this order:

1. Environment variable `SLIDE_DATA_DIR`
2. Untracked repo-local JSON file `slide_paths.json` (see `slide_paths.example.json`)
3. Default: `./SLIDE_data/` (inside the repo; recommended for most users)

The default (`./SLIDE_data/`) is intentionally untracked. Create it locally and
place/download the data there.

## Optional results directory

`get_results_dir()` similarly resolves an output directory, using:

1. Environment variable `SLIDE_RESULTS_DIR`
2. `slide_paths.json` key `results_dir`
3. Default: `./results/`

Both helpers return `pathlib.Path` objects.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Optional


def _repo_root() -> Path:
    # This file lives in the repo root.
    return Path(__file__).resolve().parent


def _read_local_config() -> dict[str, Any]:
    cfg_path = _repo_root() / "slide_paths.json"
    if not cfg_path.exists():
        return {}
    try:
        return json.loads(cfg_path.read_text())
    except Exception:
        # If config is malformed, fail softly and fall back to defaults.
        return {}


def get_slide_data_dir(*, must_exist: bool = False) -> Path:
    """Return the directory containing the large SLIDE_data files.

    Parameters
    ----------
    must_exist:
        If True, raise FileNotFoundError when the resolved directory doesn't exist.

    Returns
    -------
    pathlib.Path
    """

    env = os.getenv("SLIDE_DATA_DIR")
    if env:
        p = Path(env).expanduser().resolve()
        if must_exist and not p.exists():
            raise FileNotFoundError(f"SLIDE_DATA_DIR points to missing path: {p}")
        return p

    cfg = _read_local_config()
    cfg_val: Optional[str] = cfg.get("slide_data_dir") if isinstance(cfg, dict) else None
    if cfg_val:
        p = Path(cfg_val).expanduser().resolve()
        if must_exist and not p.exists():
            raise FileNotFoundError(f"slide_paths.json slide_data_dir missing: {p}")
        return p

    # Default: in-repo untracked data folder
    # /path/to/SLIDE/SLIDE_data
    p = (_repo_root() / "SLIDE_data").resolve()
    if must_exist and not p.exists():
        raise FileNotFoundError(
            "Couldn't find SLIDE_data. Set SLIDE_DATA_DIR or create slide_paths.json\n"
            f"Tried default: {p}"
        )
    return p


def get_results_dir(*, must_exist: bool = False) -> Path:
    """Optional: a directory for outputs outside the repo (e.g. /home/jess/Documents/results)."""

    env = os.getenv("SLIDE_RESULTS_DIR")
    if env:
        p = Path(env).expanduser().resolve()
        if must_exist and not p.exists():
            raise FileNotFoundError(f"SLIDE_RESULTS_DIR points to missing path: {p}")
        return p

    cfg = _read_local_config()
    cfg_val: Optional[str] = cfg.get("results_dir") if isinstance(cfg, dict) else None
    if cfg_val:
        p = Path(cfg_val).expanduser().resolve()
        if must_exist and not p.exists():
            raise FileNotFoundError(f"slide_paths.json results_dir missing: {p}")
        return p

    # Default: repo-root/results
    p = (_repo_root() / "results").resolve()
    if must_exist and not p.exists():
        raise FileNotFoundError(f"Results dir not found: {p}")
    return p
