"""
Figure 5E — Step 1: raw simulation data for TrpB directed evolution.

The shared N4A20 data (decay curves and strategy sweep) is generated by
delegating to Fig 5D's 1_raw_data.py. The empirical_landscape_decay_curves.py
script called there also produces the TrpB-specific decay-curve file:

  SLIDE_data/decay_curves_trpb_m0.1_multistart_10000_uniform.pkl

WARNING
-------
  strategy_sweep_TrpB_multistart_100_uniform_m0.025.pkl is required by the
  downstream data-processing step but has NO generation script on the main
  branch. This file must be present in SLIDE_data/ before proceeding to
  step 2. Contact the repository maintainer if it is missing.

Usage
-----
  python figures_src/figure_5E_TrpB_DE/1_raw_data.py

Note: requires a GPU (via the delegated 5D script).

Shared raw data: N4A20_decay_curves.pkl and N4A20_strategy_sweep.pkl are also
  used by Figs 5D and 5F.
"""

import subprocess
import sys
import os

parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

# Shared N4A20 data — delegate to 5D
script_5d = os.path.join(parent_dir, 'figures_src', 'figure_5D_GB1_DE', '1_raw_data.py')

print('Delegating to Fig 5D 1_raw_data.py for shared N4A20 data...')
result = subprocess.run([sys.executable, script_5d], cwd=parent_dir, check=True)
if result.returncode != 0:
    sys.exit(result.returncode)

print('\nDone.')
