"""
Figure 5G — Step 1: raw simulation data for ParD3 directed evolution.

Raw simulation files (all in SLIDE_data/):

  decay_curves_pard3_m0.1_multistart_10000_uniform.pkl
    — fitness decay curves for ParD3 landscape, 10000 starting points, uniform sampling
    — generated by: scripts/empirical_landscape_decay_curves_all_starts_fast.py
      (or similar empirical decay curve script with uniform starts for ParD3)

  strategy_sweep_E3_multistart_100_uniform_m0.025.pkl
    — strategy sweep over ParD3 (E3) landscape, 100 starting points, uniform sampling
    — generated by: scripts/strategy_sweep_N3A20.py (or equivalent ParD3/E3 variant)
    — NOTE: ParD3 uses a 5x5 strategy grid (N=3), unlike 7x7 for GB1/TrpB/TEV (N=4)

  SLIDE_data/N3A20_strategy_sweep.pkl   — 3-AA strategy sweep (ParD3)
  SLIDE_data/N3A20_decay_curves.pkl     — 3-AA decay curves (ParD3)

Used upstream to compute optimal_base_chances and optimal_splits lookup
(ruggedness_figures_data_processing.ipynb cells 116-119).

Landscape array:
  landscape_arrays/ParD3_landscape_array.pkl  — static empirical ParD3 fitness landscape

Usage
-----
  Generate SLIDE_data files on a GPU before proceeding to step 2:

    python scripts/empirical_landscape_decay_curves_all_starts_fast.py   # ParD3 decay curves
    python scripts/strategy_sweep_N3A20.py                                # 3-AA strategy sweep

Shared raw data: ParD3 uses a separate N=3 strategy sweep (N3A20), distinct from
  the N=4 sweeps used by Figs 5D, 5E, 5F.
"""

print("Raw data needed:")
print("  SLIDE_data/decay_curves_pard3_m0.1_multistart_10000_uniform.pkl")
print("  SLIDE_data/strategy_sweep_E3_multistart_100_uniform_m0.025.pkl")
print("  SLIDE_data/N3A20_strategy_sweep.pkl  (ParD3-specific, 3-AA grid)")
print("  SLIDE_data/N3A20_decay_curves.pkl    (ParD3-specific, 3-AA grid)")
print("  landscape_arrays/ParD3_landscape_array.pkl")
