"""
Figure 5F — Step 1: raw simulation data for TEV directed evolution.

Raw simulation files (all in SLIDE_data/):

  decay_curves_tev_m0.1_multistart_10000_uniform.pkl
    — fitness decay curves for TEV landscape, 10000 starting points, uniform sampling
    — generated by: scripts/empirical_landscape_decay_curves_all_starts_fast.py
      (or similar empirical decay curve script with uniform starts for TEV)

  strategy_sweep_TEV_multistart_100_uniform_m0.025.pkl
    — strategy sweep over TEV landscape, 100 starting points, uniform sampling
    — generated by: scripts/strategy_sweep_N4A20.py (or equivalent TEV variant)

These feed the following intermediate pkl files (shared across 5D, 5E, 5F):

  SLIDE_data/N4A20_strategy_sweep.pkl   — 4-AA strategy sweep (GB1/TrpB/TEV)
  SLIDE_data/N4A20_decay_curves.pkl     — 4-AA decay curves (GB1/TrpB/TEV)

Used upstream to compute optimal_base_chances and optimal_splits lookup
(ruggedness_figures_data_processing.ipynb cells 106-109).

Landscape array:
  landscape_arrays/TEV_landscape_array.pkl  — static empirical TEV fitness landscape

Usage
-----
  Generate SLIDE_data files on a GPU before proceeding to step 2:

    python scripts/empirical_landscape_decay_curves_all_starts_fast.py   # TEV decay curves
    python scripts/strategy_sweep_N4A20.py                                # 4-AA strategy sweep

Shared raw data: N4A20_strategy_sweep.pkl and N4A20_decay_curves.pkl are also
  used by Figs 5D and 5E.
"""

print("Raw data needed:")
print("  SLIDE_data/decay_curves_tev_m0.1_multistart_10000_uniform.pkl")
print("  SLIDE_data/strategy_sweep_TEV_multistart_100_uniform_m0.025.pkl")
print("  SLIDE_data/N4A20_strategy_sweep.pkl  (shared with Figs 5D, 5E)")
print("  SLIDE_data/N4A20_decay_curves.pkl    (shared with Figs 5D, 5E)")
print("  landscape_arrays/TEV_landscape_array.pkl")
