"""Figure S1: strategy robustness across alternative landscape models.

Compares the optimal directed-evolution strategy on three landscape families — NK,
Rough Mount Fuji (RMF), and a stochastic block model — across Low / Mid / High
ruggedness, plus the corresponding fitness-decay curves. Shows the optimum tracks
from low base-chance + low splitting to high base-chance + high splitting as
ruggedness rises, for all three models (i.e. the pipeline isn't NK-specific).

Reads 6 pre-computed sweep products from the SLIDE data directory (resolved via
``slide_config.get_slide_data_dir()`` — set ``SLIDE_DATA_DIR`` env var or drop the
files in ``SLIDE_data/``). Each is produced by a generator script in ``scripts/``:

    input file (in SLIDE_data/)                          generated by
    ---------------------------------------------------  --------------------------------------------
    landscape_comparsion_strategy_sweep_NK.pkl           strategy_sweep_alt_landscapes_NK.py
    landscape_comparsion_strategy_sweep_RMF.pkl          strategy_sweep_alt_landscapes_RMF.py
    landscape_comparsion_strategy_sweep_block.pkl        strategy_sweep_alt_landscapes_block.py
    alt_landscapes_decay_curve_sweep_NK.pkl              decay_curve_sweep_alt_landscapes_NK.py
    alt_landscapes_decay_curve_sweep_RMF.pkl             decay_curve_sweep_alt_landscapes_RMF.py
    alt_landscapes_decay_curve_sweep_blocks.pkl          decay_curve_sweep_alt_landscapes_block.py

(Those generators are GPU sweeps; run them first if the files are absent. The
landscape builders they use — RMF / stochastic block — live in direvo_functions.py.)

Run from the repository root::

    python scripts/plot_figure_s1.py

Output: figures/alt_landscapes.pdf
"""

from __future__ import annotations

import os
import sys
import pickle
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

import numpy as np
import matplotlib.pyplot as plt

from slide_config import get_slide_data_dir

# Column of strategy heatmaps + the decay-curve column; one row per landscape family.
STRATEGY_FILES = {
    "NK": "landscape_comparsion_strategy_sweep_NK.pkl",
    "RMF": "landscape_comparsion_strategy_sweep_RMF.pkl",
    "Block": "landscape_comparsion_strategy_sweep_block.pkl",
}
DECAY_FILES = {
    "NK": "alt_landscapes_decay_curve_sweep_NK.pkl",
    "RMF": "alt_landscapes_decay_curve_sweep_RMF.pkl",
    "Block": "alt_landscapes_decay_curve_sweep_blocks.pkl",
}


def _load(data_dir: Path, name: str):
    path = data_dir / name
    if not path.exists():
        raise FileNotFoundError(
            f"Missing Fig S1 input: {path}\n"
            f"Generate it with the matching scripts/*_alt_landscapes_*.py sweep (see this file's docstring)."
        )
    with open(path, "rb") as f:
        return pickle.load(f)


def main() -> None:
    """Load the 6 alternative-landscape sweep products and render figures/alt_landscapes.pdf."""
    data_dir = Path(get_slide_data_dir())
    print(f"Reading Fig S1 inputs from: {data_dir}")
    landscapes = [
        (label, _load(data_dir, STRATEGY_FILES[label]), _load(data_dir, DECAY_FILES[label]))
        for label in ("NK", "RMF", "Block")
    ]

    fig, axes = plt.subplots(nrows=3, ncols=4, figsize=(16, 10), constrained_layout=True, dpi=300)
    column_labels = ["Low", "Mid", "High", "Decay curves"]
    n_rows = len(landscapes)

    for row, (row_label, strategy_data, decay_data) in enumerate(landscapes):
        optima = []  # (x, y) per ruggedness level, for the trajectory line
        for col in range(3):
            ax = axes[row, col]
            data = strategy_data[col].mean(axis=2)
            ax.imshow(data)
            ax.set_aspect("equal", adjustable="box")
            ax.set_xticks([0, 6])
            ax.set_yticks([0, 6])
            ax.tick_params(axis="both", which="major", labelsize=10)
            if row == n_rows - 1:
                ax.set_xticklabels([0.0, 0.19])
                ax.set_xlabel("Base chance", fontsize=12)
            else:
                ax.set_xticklabels([])
            if col == 0:
                ax.set_yticklabels([24, 1])
                ax.set_ylabel("No. sub populations", fontsize=12)
            else:
                ax.set_yticklabels([])
            y_max, x_max = np.unravel_index(np.argmax(data), data.shape)
            optima.append((x_max, y_max))
            ax.plot(x_max, y_max, "o", color="white", markersize=5,
                    markeredgecolor="black", markeredgewidth=0.8, zorder=3)
            if col > 0:
                xs, ys = zip(*optima)
                ax.plot(xs, ys, "-", color="white", linewidth=1.5, alpha=0.9, zorder=2)

        ax = axes[row, 3]
        curve_labels = ["Low", "Mid", "High"]
        for n, curve in enumerate(decay_data.mean(axis=(1, 2))):
            ax.plot(curve / curve[0], label=curve_labels[n])
        ax.tick_params(axis="both", which="major", labelsize=10)
        ax.legend()
        if row == n_rows - 1:
            ax.set_xlabel("Generations", fontsize=12)
        else:
            ax.set_xticklabels([])
        ax.set_ylabel("Fitness (a.u.)", fontsize=12)

        axes[row, 0].annotate(row_label, xy=(-0.25, 0.5), xycoords="axes fraction",
                              fontsize=15, ha="right", va="center", rotation=90, fontweight="bold")

    for col, label in enumerate(column_labels):
        axes[0, col].set_title(label, fontsize=15, fontweight="bold", pad=12)
    fig.text(0.39, 1.01, "Strategy space for landscapes of increasing ruggedness",
             ha="center", va="bottom", fontsize=18, fontweight="bold")

    out = _REPO / "figures" / "alt_landscapes.pdf"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=300)
    print(f"Saved -> {out}")


if __name__ == "__main__":
    main()
